### ISSUE TITLE
Possibility to use several CIDs in test meta

### ISSUE THREAD

**Issue by moonvi** [DamianOsipiuk/testcafe-reporter-testrail#16]
Hi!

Is it possible to add using several CIDs in test meta?

My situation:
1 project (type = Use multiple test suites to manage cases)
2 suites: 1st suite contains some cases as in 2nd suite but not all

```
test.meta({ CID: 'C27988', CID: 'C91'}) // test cases in suites 1 and 2
    ('Test 2', async t => {
        //test 2
});
```

```
test.meta({ CID: 'C27987'}) // test case in 2 suite
    ('Test 1', async t => {
        //test 1
});
```

For instanse, I want to run tests from 2nd suite and have defined in env file:
`env.TESTRAIL_PROJECT_ID` = P1
`env.TESTRAIL_RUN_ID` = R123
`env.TESTRAIL_SUITE_ID` = S2

_Test Rail has:_
Test Run = **R123**
contains Suite Id = **S1**

- if run exists and CIDs found in defined run, they are not depend on SUITE ID, just PROJECT ID - apply test results based on PROJECT ID
- if run not exist and CIDs found based on SUITE ID and PROJECT ID - then new run is created
- if run exists and CID not found in run - skip test
- if run exists and at least one of the test CIDs found in run -  apply test result based on RUN ID and PROJECT ID

**Comment by DamianOsipiuk** [comment]
Hi, i would need to better understand the use case.
I believe that test run can contain only results from one test suite at a time, so attaching multiple Case IDs will not solve this problem. Also I'm not really sure if duplicating test cases between multiple test suites will be a good idea, due to higher cost of maintenance.

If you want to archive the situation when different runs are done for different test suites, and you want to provide different test case id for those, i think you can do this now using proper ENV variables configuration.
Ex.
------------------
Project - P1
Suite - S1

env.TESTRAIL_PROJECT_ID = P1
env.TESTRAIL_SUITE_ID = S1
env.TESTRAIL_CASE_META = 'S1CID'

------------------
Project - P1
Suite - S2

env.TESTRAIL_PROJECT_ID = P1
env.TESTRAIL_SUITE_ID = S2
env.TESTRAIL_CASE_META = 'S2CID'

------------------
test.meta({ S1CID: 'C123', S2CID: 'C234'})
    ('Test 1', async t => {
        //test 1
});
------------------

Then depending on the ENV variables settings proper mapping will be created.

I could provide a way to pass an array of CIDS in the same meta tag, but i feel it will be complicated, as i would have to fetch data from testrail and figure out which test case belongs to which suites, and take only ones that match.
Also after some time, You will have no idea which ID belongs to what test suite, so setting `TESTRAIL_CASE_META` would be better approach in my opinion.

**Comment by moonvi** [comment]
Great! Thank you @DamianOsipiuk 
ENV variables configuration works for me. Didn't know that.

I agree that same cases in both suites it's not a proper way to store test cases. Good news that there are not many of them (for now). If they start grow, need to review the way of store them with my teammates again.

As problem is resolved using ENV params, I think you can close this issue.
Many thanks!

**Comment by DamianOsipiuk** [comment]
I'm glad that you were able to solve the issue.
